### ISSUE TITLE
Daily StandUp 2022.07.28

### ISSUE THREAD

**Issue by JulesMorris** [Jules-Ray-Kayla-Bert-Capstone-FiFA/fifa#15]
Copy and paste your daily standup.

**Comment by JulesMorris** [comment]
Yesterday: Worked on project planning, adding tasks to project planning board, deciding positions for the the team members to focus on during EDA, and project planning docs.  
Today: Assigning EDA positions, EDA, project planning docs.
Blockers/Support Needed: None.

**Comment by EribertoContreras** [comment]
Yesterday: Started and finished acuire.py file. started prepare.py file.
Today: Finished prepare.py file
Blockers/Support Needed: N/A

**Comment by raycerna** [comment]
Yesterday: assisted with prepare functions
Today: Was assigned EDA positions, will explore on those.
Blockers/Support Needed: None.
